# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    increment_build_number(xcodeproj: "Count my breaths.xcodeproj")
    build_app(scheme: "Count my breaths")
    upload_to_testflight(
        skip_waiting_for_build_processing: true,
        apple_id: "1513102381"
    )
    commit_version_bump(xcodeproj: "Count my breaths.xcodeproj")
    add_git_tag
    push_to_git_remote
  end

  lane :major do
    ensure_git_status_clean
    # increment_version_number(bump_type: "major")
    increment_build_number(xcodeproj: "Count my breaths.xcodeproj")
    # sync_code_signing(type: "appstore")
    build_app(scheme: "Count my breaths")
    upload_to_testflight(
        skip_waiting_for_build_processing: true,
        apple_id: "1513102381"
    )
    commit_version_bump(xcodeproj: "Count my breaths.xcodeproj")
    add_git_tag
    push_to_git_remote
  end

  lane :minor do
    ensure_git_status_clean
    # increment_version_number(bump_type: "minor")
    increment_build_number(xcodeproj: "Count my breaths.xcodeproj")
    # sync_code_signing(type: "appstore")
    build_app(scheme: "Count my breaths")
    upload_to_testflight(
        skip_waiting_for_build_processing: true,
        apple_id: "1513102381"
    )
    # upload_to_app_store
    commit_version_bump(xcodeproj: "Count my breaths.xcodeproj")
    add_git_tag
    push_to_git_remote
  end

  lane :patch do
    ensure_git_status_clean
    # increment_version_number(bump_type: "patch")
    increment_build_number(xcodeproj: "Count my breaths.xcodeproj")
    # sync_code_signing(type: "appstore")
    build_app(scheme: "Count my breaths")
    upload_to_testflight(
        skip_waiting_for_build_processing: true,
        apple_id: "1513102381"
    )
    commit_version_bump(xcodeproj: "Count my breaths.xcodeproj")
    add_git_tag
    push_to_git_remote
  end

  lane :bump_major do
    increment_version_number(bump_type: "major")
    increment_build_number(xcodeproj: "Count my breaths.xcodeproj")
    commit_version_bump(xcodeproj: "Count my breaths.xcodeproj")
    add_git_tag
  end

  lane :bump_minor do
    increment_version_number(bump_type: "minor")
    increment_build_number(xcodeproj: "Count my breaths.xcodeproj")
    commit_version_bump(xcodeproj: "Count my breaths.xcodeproj")
    add_git_tag
  end

  lane :bump_patch do
    increment_version_number(bump_type: "patch")
    increment_build_number(xcodeproj: "Count my breaths.xcodeproj")
    commit_version_bump(xcodeproj: "Count my breaths.xcodeproj")
    add_git_tag
  end

end
