name: CICD
on:
  push:
    branches:
    - feat/*
jobs:
  beta:
    name: Publish to TestFlight
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup environment
        run: |
          sudo xcode-select -switch /Applications/Xcode_11.3.app
          /usr/bin/xcodebuild -version
          sh -x ./env.sh
      - name: Install dependencies
        run: brew bundle
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: sh -x ./.github/secrets/decrypt_secrets.sh
      - name: Git status
        run: git status
      - name: Publish beta
        run: fastlane beta

