name: CI
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - master
jobs:
  test:
    # Job name is test
    name: Test
    # This job runs on macOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      - name: App version
        run: |
          xcrun agvtool what-version
          xcrun agvtool what-marketing-version
      - name: Install gpg
        run: brew install gnupg
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: sh -x ./.github/secrets/decrypt_secrets.sh
      - name: Archiving project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: sh -x ./.github/scripts/archive_app.sh
      - name: Exporting .ipa
        run: sh -x ./.github/scripts/export_ipa.sh
      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: sh -x ./.github/scripts/publish_testflight.sh
