name: Release
on:
  push:
    branches:
    - 'master'
jobs:
  publish:
    name: Publish to AppStore
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Setup environment
        env: 
          GITHUB_REF: ${{ secrets.GITHUB_REF }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          /usr/bin/xcodebuild -version
          sh -x ./env.sh
      - name: Install dependencies
        run: bundle update --bundler
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: sh -x ./.github/secrets/decrypt_secrets.sh
      - name: build
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 600
        run: bundle exec fastlane release
